version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_service
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_service
    depends_on:
      - server
    ports:
      - "5173:5173"
    networks:
      - app_network
    restart: always

networks:
  app_network:
